// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vIQ_LSp5PHV0VStiqRJrrj3q9X4uWqk',
    appId: '1:338185842132:web:a911121c0ac431898a3a41',
    messagingSenderId: '338185842132',
    projectId: 'cryptocoinslist-6fd6b',
    authDomain: 'cryptocoinslist-6fd6b.firebaseapp.com',
    storageBucket: 'cryptocoinslist-6fd6b.appspot.com',
    measurementId: 'G-YX0425GYX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3l-7_4jC3myMZ2RrtF8WT3uzghGKRq5k',
    appId: '1:338185842132:android:6ca92ed11f9641b48a3a41',
    messagingSenderId: '338185842132',
    projectId: 'cryptocoinslist-6fd6b',
    storageBucket: 'cryptocoinslist-6fd6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrkBBBdz8UnFoOx4fXize9vNnbHg1u78I',
    appId: '1:338185842132:ios:641574a917f79cff8a3a41',
    messagingSenderId: '338185842132',
    projectId: 'cryptocoinslist-6fd6b',
    storageBucket: 'cryptocoinslist-6fd6b.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );
}
